services:
  - type: web
    name: streamlit-dashboard
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run dashboard.py"
>>>>>>> 31e689760cdec86ea791db2580be3ea83470da7e
